#ifndef COLORS_H_
#define COLORS_H_

#include <stdint.h>

// Color constants in BGR565 format
// Generated by RayCast3D Studio

#define SLATE 0xC530  // RGB(129, 166, 192)
#define FORESTGREEN 0x4400  // RGB(0, 128, 64)

#endif /* COLORS_H_ */